### ISSUE TITLE
Autoloading broken on Rails 7

### ISSUE THREAD

**Issue by pelargir** [solidusio-contrib/solidus_reviews#112]
Autoloading is broken on Rails 7 due to referencing a constant in the `load_preferences.rb` initializer:

```in `<module:Reviews>': uninitialized constant Spree::ReviewsConfiguration (NameError)```

[This PR](https://github.com/solidusio-contrib/solidus_reviews/pull/110) fixes the problem.

**Comment by pelargir** [comment]
The fix has been merged.

**Comment by yousamaa** [comment]
I am using version 1.5 and it still breaks with rails 7.0. I cannot upgrade to 1.6 as I am using ruby 2.7.8. I cannot upgrade my ruby as I am using solidus_affirm_v2 too which is not support by ruby 3.0 yet.
