### ISSUE TITLE
Need add key to translate file ru.yml

### ISSUE THREAD

**Issue by StanZhuravlev** [solidusio-contrib/solidus_reviews#23]
Hi!

After install your module, I see a missing transaltion key 

> ru.spree.admin.tab.reviews

Can you add it and put **Отзывы** for him? 

Best,
Stan

**Comment by tvdeyen** [comment]
Appreciate any contributions. Meanwhile create the translation under the same key in your local locale file to fix the issue.

**Comment by jtapia** [comment]
@tvdeyen I think we can close this issue, what do you think?

**Comment by tvdeyen** [comment]
Yes. Thanks
