### ISSUE TITLE
Support rating only reviews

### ISSUE THREAD

**Issue by joelsaupe** [solidusio-contrib/solidus_reviews#41]
Requiring users to fill out their name / message can discourage users from leaving a review. Currently users can't leave a review with just a rating, but doing so would make it more accessible to users willing to at least leave a rating without a message. This is also a pretty common ability with most rating/review systems.

### Expectations 
I would expect that if a user leaves only a rating, it would bypass the approval system. If a user leaves a rating only review, they should be able to add a full review at a later time (edit their review). If a user edits their rating only review to add content, I would expect it to go back through the approval system, BUT I would think the rating should still be used as part of the total average rating. I would think this would mean that all reviews would have their rating counted as part of the average rating whether they're pending/approved/rejected.

**Comment by ericsaupe** [comment]
Closed with #42, #44
