### ISSUE TITLE
Class variable access from toplevel

### ISSUE THREAD

**Issue by ericsaupe** [solidusio-contrib/solidus_reviews#47]
Fix warning found when starting up the app

https://github.com/solidusio-contrib/solidus_reviews/blob/master/app/helpers/spree/api/api_helpers_decorator.rb#L4

https://github.com/solidusio-contrib/solidus_reviews/blob/master/app/helpers/spree/api/api_helpers_decorator.rb#L10

`warning: class variable access from toplevel`

**Comment by aldesantis** [comment]
Closing, as I think we're good now.
