### ISSUE TITLE
uninitialized constant SolidusReviews::Spree::Admin (NameError)

### ISSUE THREAD

**Issue by nkhdo** [solidusio-contrib/solidus_reviews#77]
Hello,

I got this error after deploying to production server (it works well on my local):

```
 uninitialized constant SolidusReviews::Spree::Admin (NameError)
```
After checking, I found that I have to disable eager_load on production env for it to works

```ruby
# environment/production.rb
config.eager_load = false
```
However this would affect my app performance. I still can not find out the root cause. Please help!

Thanks in advance!

P/S: My production system
- ubuntu 18.04
- ruby 2.6.3
- rails 6.0.2.1
- solidus_review 1.3.0

**Comment by aldesantis** [comment]
@nkhdo fixed in master now!
