### ISSUE TITLE
Cannot select star rating when creating or editing a review

### ISSUE THREAD

**Issue by dhughesbc** [solidusio-contrib/solidus_reviews#88]
When creating a review as a customer or when editing a review as an admin, clicking on the ratings links does nothing. There is no JS error in the console. All other review functionality seems to be working as intended.

![Screenshot from 2020-07-13 13-29-14](https://user-images.githubusercontent.com/2659218/87334596-e88c2700-c50c-11ea-9ece-e8cab0294a75.png)

I am using a fresh install of Solidus with the default storefront.
```
ruby '2.7.1'
gem 'rails', '~> 6.0.3', '>= 6.0.3.2'
gem 'solidus', '~> 2.10.1'
gem 'solidus_auth_devise', '~> 2.4.0'
gem 'solidus_reviews', github: 'solidusio-contrib/solidus_reviews'
```

**Comment by dhughesbc** [comment]
The issue is related to css styles missing. There is a .css and a .scss file in https://github.com/solidusio-contrib/solidus_reviews/tree/master/app/assets/stylesheets/spree/frontend. The .css file, which contains no styles, is getting complied into the main all.css file, and the .scss, which does have style info, seems to getting ignored.

**Comment by aldesantis** [comment]
@dhughesbc thanks for catching! Would you have a minute to open a PR and address this? 🙂

**Comment by dhughesbc** [comment]
@aldesantis If it is just a matter of removing the empty .css file, I can open a PR. I just wasn't sure if it had been added for some specific reason.

**Comment by aldesantis** [comment]
@dhughesbc yep, I think the file is just there by mistake.
