### ISSUE TITLE
Broken HTML link in review edit screen

### ISSUE THREAD

**Issue by dhughesbc** [solidusio-contrib/solidus_reviews#89]
At the top of the edit screen for an individual review, there is HTML displayed:

Editing review for <a href="/products/solidus-t-shirt">Solidus T-Shirt</a>

![Screenshot from 2020-07-13 15-56-27](https://user-images.githubusercontent.com/2659218/87347817-d1a3ff80-c521-11ea-80e9-4eda4f247255.png)

**Comment by dhughesbc** [comment]
resolved by https://github.com/solidusio-contrib/solidus_reviews/pull/90

**Comment by memotoro** [comment]
Hello @dhughesbc I have created a PR fixing the title as the translation template is not intended to be used to create links. It is just creating text and the link is obviously not working. Have a look to the PRs and you will get this fix. Regards

**Comment by kennyadsl** [comment]
Fixed with https://github.com/solidusio-contrib/solidus_reviews/pull/91, thanks @memotoro
